services:
  - type: web
    name: ssh-nexjs
    env: python
    region: oregon
    plan: free
    buildCommand: |
      cd backend
      pip install -r requirements.txt
    startCommand: |
      cd backend
      gunicorn --config gunicorn.conf.py app:app
    envVars:
      - key: RENDER
        value: "true"
      - key: PYTHONUNBUFFERED
        value: "1"
      - key: PYTHONDONTWRITEBYTECODE
        value: "1" 